#!/usr/bin/env bash
### To reproduce the curves, one has to run all the models for seed in {0, 1, 2, 3, 4}, and then average the results

# FGSM
python train.py --dataset=svhn --attack=fgsm --eps=1  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=2  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=3  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=4  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=5  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=6  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=7  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=8  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=9  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=10  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=11  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=12  --attack_init=zero --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0

# FGSM-RS
python train.py --dataset=svhn --attack=fgsm --eps=1  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=2  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=3  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=4  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=5  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=6  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=7  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=8  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=9  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=10  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=11  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=12  --attack_init=random --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0

# GradAlign: the log-linear interpolation scheme: exp(eps * 1/8*ln(1.6) + ln(2.5**2/4.0))
python train.py --dataset=svhn --attack=fgsm --eps=1  --attack_init=zero --epochs=15 --grad_align_cos_lambda=1.657 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=2  --attack_init=zero --epochs=15 --grad_align_cos_lambda=1.757 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=3  --attack_init=zero --epochs=15 --grad_align_cos_lambda=1.864 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=4  --attack_init=zero --epochs=15 --grad_align_cos_lambda=1.976 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=5  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.096 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=6  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.223 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=7  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.357 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=8  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.500 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=9  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.651 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=10  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.812 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=11  --attack_init=zero --epochs=15 --grad_align_cos_lambda=2.982 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=12  --attack_init=zero --epochs=15 --grad_align_cos_lambda=3.162 --lr_max=0.30 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0

# PGD-2
python train.py --dataset=svhn --attack=pgd --eps=1  --attack_init=zero --pgd_alpha_train=0.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=2  --attack_init=zero --pgd_alpha_train=1.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=3  --attack_init=zero --pgd_alpha_train=1.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=4  --attack_init=zero --pgd_alpha_train=2.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=5  --attack_init=zero --pgd_alpha_train=2.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=6  --attack_init=zero --pgd_alpha_train=3.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=7  --attack_init=zero --pgd_alpha_train=3.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=8  --attack_init=zero --pgd_alpha_train=4.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=9  --attack_init=zero --pgd_alpha_train=4.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=10  --attack_init=zero --pgd_alpha_train=5.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=11  --attack_init=zero --pgd_alpha_train=5.5 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=12  --attack_init=zero --pgd_alpha_train=6.0 --pgd_train_n_iters=2 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0

# PGD-10
python train.py --dataset=svhn --attack=pgd --eps=1  --attack_init=zero --pgd_alpha_train=0.2 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=2  --attack_init=zero --pgd_alpha_train=0.4 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=3  --attack_init=zero --pgd_alpha_train=0.6 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=4  --attack_init=zero --pgd_alpha_train=0.8 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=5  --attack_init=zero --pgd_alpha_train=1.0 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=6  --attack_init=zero --pgd_alpha_train=1.2 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=7  --attack_init=zero --pgd_alpha_train=1.4 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=8  --attack_init=zero --pgd_alpha_train=1.6 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=9  --attack_init=zero --pgd_alpha_train=1.8 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=10  --attack_init=zero --pgd_alpha_train=2.0 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=11  --attack_init=zero --pgd_alpha_train=2.2 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=pgd --eps=12  --attack_init=zero --pgd_alpha_train=2.4 --pgd_train_n_iters=10 --epochs=15 --lr_max=0.05 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0

# Free-AT
python train.py --dataset=svhn --attack=fgsm --eps=1 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=2 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=3 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=4 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=5 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=6 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=7 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=8 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=9 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=10 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=11 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
python train.py --dataset=svhn --attack=fgsm --eps=12 --attack_init=zero --fgsm_alpha=1.0 --minibatch_replay=8 --epochs=45 --lr_max=0.01 --eval_iter_freq=200 --batch_size_eval=1024 --half_prec --eval_early_stopped_model --n_final_eval=1000 --seed=0
